export const giftsVoucherTabTitleContent={
    giftAvoucherEn:"Gift a voucher",
    giftAvoucherAr:"الهدايا المرسلة",
    sendGiftEn:"Send gift",
    sendGiftAr:"هدية قسيمة",
}
export const addressesSectionContent = 
    {
        addressEn:"Address",
        addressAr:"عناوين",
        otherAddressEn:"Other Address",
        otherAddressAr:"عنوان آخر",
        addAnewAddressEn:"Add A New Address",
        addAnewAddressAr:"أضف عنوانا جديدا",
    }
export const addressesCardContent = 
    {
        defaultEn:"Default",
        defaultAr:"الأفتراضي",
        makeDefaultBtnEn:"make default",
        makeDefaultBtnAr:"الأفتراضي",
        deleteBtnEn:'Delete',
        deleteBtnAr:'مسح',
        editBtnEn:"Edit",
        editBtnAr:"تحرير",
    }
export const favoriteSectionContent = 
    {
        myFavoriteEn:"My Favorite (1)",
        myFavoriteAr:"مفضلتي (1)",
        moveToCartBtnEn:"Move To Cart",
        moveToCartBtnAr:"أنقل ألي الكرت",
    }
export const balancedValueCardContent = 
    {
        balanceValueTitleEn:"Balance Value*",
        balanceValueTitleAr:"قيمة الرصيد *",
        btnSar50En:"SAR 50",
        btnSar50Ar:"50 ريال",
        btnSar100En:"SAR 100",
        btnSar100Ar:"100 ريال",
        btnSar200En:"SAR 200",
        btnSar200Ar:"200 ريال",
        btnSar500En:"SAR 500",
        btnSar500Ar:"500 ريال",
        anotherValueEn:"Another Value",
        anotherValueAr:"قيمة أخرى",
    }
export const voucherFormContent = 
    {
        recipientDetailsEmailEn:"Recipient-details email",
        recipientDetailsEmailAr:"البريد الإلكتروني تفاصيل المستلم",
        phoneEn:"Phone/Mobile",
        phoneAr:"الهاتف المحمول",
        recipientNameEn:"Recipient name",
        recipientNameAr:"اسم المستلم *",
        senderNameEn:"Sender name",
        senderNameAr:"اسم المرسل *",
        msgEn:" Message",
        msgAr:"رسالة",
        toViewVoucherPolicyEn:"To View Voucher Policy",
        toViewVoucherPolicyAr:"لعرض سياسة القسيمة",
        clickHereEn:" Click Here",
        clickHereAr:" انقر هنا",
        submitBtnEn:"Submit",
        submitBtnAr:"أتمام",
    }
export const giftSendAccordionContent = 
    {
        giftIdEn:"Gift ID:",
        giftIdAr:"معرف الهدية :",
        recipientDetailsEmail2En:"Recipient-details email:",
        recipientDetailsEmail2Ar:":البريد الإلكتروني تفاصيل المستلم",
        mobileEn:"Phone/Mobile:",
        mobileAr:":الهاتف المحمول",
        recipientName2En:"Recipient name:",
        recipientName2Ar:":اسم المستلم ",
        senderName2En:"Sender name:",
        senderName2Ar:":اسم المرسل ",
        balanceValue2En:"Balance Value:",
        balanceValue2Ar:"قيمة الرصيد :",
        dateEn:"Date:",
        dateAr:"تاريخ :",
        messageEn:" Message:",
        messageAr:":رسالة",
        voucherPolicyEn:"To View Voucher Policy",
        voucherPolicyAr:"لعرض سياسة القسيمة",
        clickHere2En:" Click Here",
        clickHere2Ar:" انقر هنا",
        submitBtnTextEn:"Submit",
        submitBtnTextAr:"أتمام",
    }
export const profileSectionContent = 
    {
        profileTitleEn:"Profile",
        profileTitleAr:"الملف الشخصي",
        firstNameEn:"First name",
        firstNameAr:"الاسم الاول ",
        lastNameEn:"Last name",
        lastNameAr:"الاسم الاخير",
        emailEn:"Email",
        emailAr:"البريد الالكتروني",
        labelPhonEn:"Phone/Mobile",
        labelPhonAr:"رقم الهاتف / الجوال",
        genderEn:"Gender",
        genderAr:"النوع",
        salmanEn:"Salman",        
        salmanAr:"Salman",        
        mirEn:"Mir",        
        mirAr:"Mir",        
        salmanGmailEn:"Salman@gmail.com",        
        salmanGmailAr:"Salman@gmail.com",        
        placeholderNumberEn:"966123456789",        
        placeholderNumberAr:"966123456789",        
        maleEn:"Male",        
        maleAr:"Male",    
        editProfileBtnEn:"Edit Profile",
        editProfileBtnAr:"تعديل الملف",
    }
export const ticketCardContent = 
    {
        titleActiveEn:"Will be closed permanently in 72 hours",
        titleActiveAr:"سيتم إغلاقه نهائيًا خلال 72 ساعة",
        titleCloseEn:"Ticket Closed",
        titleCloseAr:"التذكرة مغلقة",
        ticketNoEn:"Ticket Number:",
        ticketNoAr:"رقم التذكرة:",
        reasonTextEn:"Reason:",
        reasonTextAr:"اخر تحديث:",
        dateTextEn:"Date:",
        dateTextAr:"تاريخ:",
        lastUpdateEn:"Last update:",
        lastUpdateAr:"سبب:",
        hfjjjkd6239En:"#6272362736239hfjjjkd",        
        hfjjjkd6239Ar:"#6272362736239hfjjjkd",        
        extraItemsEn:"Extra Items",        
        extraItemsAr:"Extra Items",        
        timeTextEn:"10/8/2023 11:33:7 PM",        
        timeTextAr:"10/8/2023 11:33:7 PM",        
        lastUpdateTimeEn:"14/8/2023 7:30:00 AM",        
        lastUpdateTimeAr:"14/8/2023 7:30:00 AM",
    }
export const transactionCardContent = 
    {
        transactionEn:"Transaction",
        transactionAr:"العملية",
        theAmountEn:"The amount",
        theAmountAr:"المبلغ",
        addToYourAccountEn:"Add to your account: #86",
        addToYourAccountAr:"أضف إلى حسابك: #86",
        paymentOrderEn:"Payment order: #546",
        paymentOrderAr:"أمر الدفع: #546",
        moneyBackEn:"Money back: #546",
        moneyBackAr:"استرداد الأموال: #546",
        date10En:"10/8/2023",
        date10Ar:"10/8/2023",
        date8En:"10/8/2023",
        date8Ar:"10/8/2023",
        date2023En:"10/8/2023",
        date2023Ar:"10/8/2023",
        amountSarEn:"400 SAR",
        amountSarAr:"400 SAR",
        amountSar2En:"400 SAR",
        amountSar2Ar:"400 SAR",
        amountSar3En:"400 SAR",
        amountSar3Ar:"400 SAR",
    }
