export const footerContactContent={
    getInTouchEn:"GET In Touch",
    getInTouchAr:" قنوات الدعم",
    followUsEn:"Follow Us In Social media",
    followUsAr:"تواصل معنا عبر أي من قنوات الدعم هذه",
    helpTextEn:" We are always here to help",
    helpTextAr:"نحن دائما هنا المساعدة",
    helpDescriptionEn:"Reach out to us through any of these support channels",
    helpDescriptionAr:"تواصل معنا عبر أي من قنوات الدعم هذه",
    helpCenterEn:"Help Center",
    helpCenterAr:"اتصل بنا",
    contactUsEn:"Contact us",
    contactUsAr:"مركز المساعدة",
    subscribeEn:"Subscribe to our Awesome emails",
    subscribeAr:"اشترك في رسائل البريد الإلكتروني الرائعة لدينا",
    subDetailEn:"Get our latest offers and news straight In your inbox",
    subDetailAr:"احصل على أحدث عروضنا وأخبارنا مباشرة في بريدك الوارد",
    enterYourMailEn:"Enter your email",
    enterYourMailAr:"ادخل بريدك الالكتروني",
    btnTextEn:"Send",
    btnTextAr:"ارسال",
}