export const itemPageContent = {
  breadcrumbsEn: 'Home / Brands / Dietary Supplements / Brands / Brands',
  breadcrumbsAr:
    'الرئيسية / الماركات / المكملات الغذائية / الماركات / الماركات',
};
export const itemsContent = {
  exclusiveProductLogoEn: '/images/items/naruto.png',
  exclusiveProductLogoAr: '/images/items/naruto.png',
  exclusiveProductBrandNameEn: 'NARUTO',
  exclusiveProductBrandNameAr: 'NARUTO',
  exclusiveProductTextEn: 'For more of our exclusive products,',
  exclusiveProductTextAr: 'لمزيد من منتجاتنا الحصرية،',
  exclusiveProductLinkTextEn: ' click here',
  exclusiveProductLinkTextAr: 'انقر هنا',
  exclusiveProductLinkUrlEn: '',
  exclusiveProductLinkUrlAr: '',
  btsMusicAlbumEn: 'BTS music album',
  btsMusicAlbumAr: 'تي شيرت مخصص للرجال وللنساء',
  releaseDateEn: 'Release date',
  releaseDateAr: 'تاريخ الاصدار',
  dateEn: '6/16 /2023',
  dateAr: '6/16 /2023',
  preOrderEn: 'Pre order',
  preOrderAr: 'طلب مسبق',
  availableGiftsEn: 'Gifts are available upon request during the pre-order period',
  availableGiftsAr: 'متوفرة الهدايا عند طلب في فترة الطلب المسبق',
  prevPriceEn: '33.92',
  prevPriceAr: '33.92',
  discountRateEn: '20',
  discountRateAr: '20',
  priceEn: '27.15',
  priceAr: '27.15',
  currencyEn: '$',
  currencyAr: '$',
  gifTitleEn: 'Gifts',
  gifTitleAr: 'هدايه',
  imgEn: [
    { color: 'green', src: '/images/items/tshirt2.png' },
    { color: 'blue', src: '/images/items/tshirt.png' },
    { color: 'red', src: '/images/items/tshirt3.png' },
    { color: 'orange', src: '/images/items/tshirt4.png' },
    { color: 'sky-blue', src: '/images/items/tshirt5.png' },
  ],
  imgAr: [
    { color: 'green', src: '/images/items/tshirt2.png' },
    { color: 'blue', src: '/images/items/tshirt.png' },
    { color: 'red', src: '/images/items/tshirt3.png' },
    { color: 'orange', src: '/images/items/tshirt4.png' },
    { color: 'sky-blue', src: '/images/items/tshirt5.png' },
  ],
  colorCaptionEn: 'Color',
  colorCaptionAr: 'Color',
  sizeCaptionEn: 'Size',
  sizeCaptionAr: 'المقاس',
  sizesArrayEn: ['XS', 'S', 'M', 'L', 'XL'],
  sizesArrayAr: ['XS', 'S', 'M', 'L', 'XL'],
  paymentTextEn: 'or 4 interset-free paymnets of',
  paymentTextAr: 'أو 4 شبكات دفع مجانية بقيمة',
  paymentAmountEn: 'SAR 260.80',
  paymentAmountAr: '260.80 ريال',
  paymentText2En: 'Split in up to 4 interset-free payments of',
  paymentText2Ar: 'مقسمة على ما يصل إلى 4 دفعات بدون إنترنت بقيمة',
  paymentAmount2En: 'SAR 260.81',
  paymentAmount2Ar: '260.81 ريال سعودي',
  spanTextEn: 'or pay in full!',
  spanTextAr: 'أو الدفع بالكامل!',
  learnTextEn: ' Learn More',
  learnTextAr: 'أعلم المزيد',
  learnUrlEn: '',
  learnUrlAr: '',
  learnMoreTextEn: ' Learn More',
  learnMoreTextAr: 'أعلم المزيد',
  learnMoreUrlEn: '',
  learnMoreUrlAr: '',
  addToCartBtnTextEn: 'Add to cart',
  addToCartBtnTextAr: 'أضف للسلة',
};
export const itemImageContent = {
  imgEn: '/images/items/tshirt.png',
  imgAr: '/images/items/tshirt.png',
  img2En: '/images/items/itemVari.png',
  img2Ar: '/images/items/itemVari.png',
  img3En: '/images/items/itemVari.png',
  img3Ar: '/images/items/itemVari.png',
  img4En: '/images/items/itemVari.png',
  img4Ar: '/images/items/itemVari.png',
};
export const serviceOfferContent = {
  freeDeliveryEn: 'free delivery',
  freeDeliveryAr: 'توصيل مجاني',
  freeDeliveryDetailsEn: 'Free delivery on all orders Purchase with a value of more than 399 riyals',
  freeDeliveryDetailsAr: 'توصيل مجاني لجميع الطلبات عند الشراء بقيمة تزيد عن 399 ريال',
  freeExchangeEn: 'Free exchange within 14 days',
  freeExchangeAr: 'استبدال مجاني خلال 14 يوم',
  freeExchangeDetailsEn:'Replacement or money back guarantee For all orders within 14 days of purchase',
  freeExchangeDetailsAr:'ضمان استبدال أو استرداد الاموال لجميع الطلبات خلال 14 يوم من الشراء',
  paymentWhenReceivingEn: 'Paiement when recieving',
  paymentWhenReceivingAr: 'الدفع عند الاستلام',
  paymentWhenReceivingDetailsEn: 'To ensure the comfort of customersand gain their trust',
  paymentWhenReceivingDetailsAr: 'لضمان راحة الزبائن وكسب ثقتهم',
  poweredByEn: 'Powered by',
  poweredByAr: 'مدعوم من قبل',
  poweredByDetailsEn: 'All of our albums count Hanteo and Gaon diagram',
  poweredByDetailsAr: 'جميع البوماتنا تحسب ضمن مخطط هانتيو وقاون',
};
export const itemAboutContent = {
  youTubeVideoEn: 'YouTube Video',
  youTubeVideoAr: 'لينك اليوتيوب',
  headingProfessionalEn: 'Professional 2-in-1 Hair Straightening and Drying Brush from Ola Hair:',
  headingProfessionalAr: 'فرشاة تصفيف وتجفيف الشعر الاحترافية 2 في 1 من اولا هير:',
  hairListEn: 'Hair styler works to dry hair from water and style it at the same time.',
  hairListAr: 'جهاز تصفيف الشعر يعمل على تجفيف الشعر من الماء وتصفيفه في آن واحد.',
  featureListEn: 'It features ionic technology that makes your hair smooth and frizz-free.',
  featureListAr: 'تتميز بتقنية الايونات التي تجعل شعرك ناعما بلا تطاير.',
  settingListEn: 'It has three different settings: high, low, and cooling, so you canchoose the right degree for your hair type.',
  settingListAr: 'يحتوي على ثلاثة إعدادات مختلفة هي مرتفع ومنخفض وخاصية التبريد لتختاري الدرجة المناسبة لنوع شعرك.',
  smoothingListEn: 'Smoothing, drying, straightening, styling and polishing hair brush in one.',
  smoothingListAr: 'فرشاة تنعيم وتجفيف وفرد وتصفيف الشعر وتلميعه في منتج واحد.',
  productInfoEn: 'Product information:',
  productInfoAr: 'معلومات المنتج:',
  cableLengthEn: 'Cable length:',
  cableLengthAr: 'طول الكيبل:',
  voltageEn: 'Voltage:',
  voltageAr: 'الجهد:',
  powerEn: 'Power:',
  powerAr: 'القوة: ',
  modelNumberEn: 'Model number:',
  modelNumberAr: 'رقم الموديل: ',
  warrantyEn: 'Warranty:',
  warrantyAr: 'الضمان:',
  meters3En: '3 meters.',
  meters3Ar: ' 3 متر.',
  volts240En: '220-240 volts.',
  volts240Ar: '220-240 فولت.',
  wats1200En: '1200 watts.',
  wats1200Ar: '1200 واط.',
  ol1010En: ' OL-1010.',
  ol1010Ar: 'OL-1010.',
  years2En: '2 years.',
  years2Ar: 'سنتين.',
};
export const itemReviewContent = {
  reviewCountEn: '5',
  reviewCountAr: '5',
  basedOn323ReviewsEn: ' Based on 323 reviews',
  basedOn323ReviewsAr: ' بناء على 323 تقيمات',
  recentlyAddedBtnTextEn: 'Recently added',
  recentlyAddedBtnTextAr: 'أضيفت مؤخراً',
  recentlyAddedBtnText2En: 'Recently added',
  recentlyAddedBtnText2Ar: 'أضف تقيمك',
  nameEn: 'salman',
  nameAr: 'salman',
  date626En: '6-26-2023',
  date626Ar: '6-26-2023',
  reviewCommentEn: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the Lorem Ipsum has been the Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsu',
  reviewCommentAr: 'برو سبس ليست مجرَد منتج، فهي أسلوب حياة. وهي ليست مجرَد متجر، بل إنها ثورة بحد ذاتها. يطمح كل فرد من عائلة برو سبس بأن تصبح الشركة أشهر شركة مكمِلات رياضية في العالم، لتساعدك على أن تصبح أقوى وأعظم ممَا أنت عليه الآن.',
  showMoreTextEn: 'Show more',
  showMoreTextAr: 'عرض المزيد',
  allReviewTextEn: 'All reviews',
  allReviewTextAr: 'أضف تقيمك',
  addYourReviewTextEn: 'Add your review',
  addYourReviewTextAr: 'كل التقيمات',
};

export const relatedProductCardContent = {
  imgEn: '/images/items/02.png',
  imgAr: '/images/items/02.png',
  offerEn: 'New',
  offerAr: 'جديد',
  nameShampoEn: 'Shampo',
  nameShampoAr: 'شامبو',
  shampoDetailEn: "Intea Children's Shampo Blond Highlights 250ml",
  shampoDetailAr: 'شامبو إنتيا للأطفال، أشقر، 250 مل',
  textAddToCartEn: 'ADD TO CART',
  textAddToCartAr: 'أضافه الي العربه',
  prevPriceSar125En: 'SAR125',
  prevPriceSar125Ar: 'SAR125',
  price25En: '25',
  price25Ar: '25',
  dicount10En: '20',
  dicount10Ar: '20',
};
