export const orderProcessContent={
  orderCreatedEn:"Order Created ",
  orderCreatedAr:"انشاء الطلب",
  inProcessingEn:"In Processing ",
  inProcessingAr:"انشاء الطلب",
  withCourierEn:"With Courier ",
  withCourierAr:"مع ساعي",
  deliveredEn:"Delivered ",
  deliveredAr:"تم التوصيل",
  orderDetailLinkTextEn:"Drder Details",
  orderDetailLinkTextAr:"تفاصيل الطلب",
  itemTextEn:"Item",
  itemTextAr:"عنصر ",
}
export const myOrderDetailsContent={
  orderDetailsTitleEn:"Order Details",
  orderDetailsTitleAr:"تفاصيل الطلب",
  orderCreatedEn:"Order Created ",
  orderCreatedAr:"انشاء الطلب",
  orderConfirmationEn:"Order Confirmation",
  orderConfirmationAr:"قيد الانتظار",
  inProcessingEn:"In Processing ",
  inProcessingAr:"انشاء الطلب",
  withCourierEn:"With Courier ",
  withCourierAr:"مع ساعي",
  deliveredEn:"Delivered ",
  deliveredAr:"تم التوصيل",
  orderDetailLinkTextEn:"Drder Details",
  orderDetailLinkTextAr:"تفاصيل الطلب",
  issuesWithOrderEn:"Do You have any issues with your order ?",
  issuesWithOrderAr:"هل لديك أي مشاكل مع طلبك؟",
  addNewTicketBtnEn:" Add New Tickets",
  addNewTicketBtnAr:"إضافة تذاكر جديدة",
  noTicketAvailableEn:"No Ticket Available",
  noTicketAvailableAr:"إجمالي التذاكر",
  processingEn:"processing",
  processingAr:"قيد المعالجة",
  pendingEn:"pending",
  pendingAr:"قيد الانتظار",
  cancelEn:"cancel",
  cancelAr:"الغاء",
  returnRequestEn:"Return Request",
  returnRequestAr:"طلب ارجاع",
  cancelReturnRequestEn:"Cancel Return Request",
  cancelReturnRequestAr:"الغاء طلب ارجاع",
  cancelOrEditEn:"Cancel Or Edit",
  cancelOrEditAr:"الغاء",
  contactCustomerCareEn:"Contact Customer Care",
  contactCustomerCareAr:"تواصل مع خدمة العملاء",
}
export const myOrderAddressContent={  
  orderAddressTitleEn:"Address",
  orderAddressTitleAr:"العنوان",
  abdallhElzayatEn:"Abdallh Elzayat 123456123",
  abdallhElzayatAr:"عبدالله الزيات 123456123 ",
  yourAddressHereEn:"Your Address Here",
  yourAddressHereAr:"عنوانك هنا",
}
export const myOrderPaymentContent={ 
  paymentMethodEn:"Payment Method",
  paymentMethodAr:"طريقة الدفع او السداد",
  cashOnDeliveryEn:"Cash on Delivery",
  cashOnDeliveryAr:"الدفع عند الاستلام",
}
export const myOrderSummaryContent={ 
  orderSummaryEn:"Order Summary",
  orderSummaryAr:"ملخص الطلب",
  subTotalEn:"Sub Total",
  subTotalAr:"المجموع الفرعي",
  shippingFeeEn:"Shipping Fee",
  shippingFeeAr:"رسوم الشحن",
  cashOnDeliveryFeeEn:"Cash on Delivery Fee",
  cashOnDeliveryFeeAr:"رسوم الدفع عند التسليم",
  grandTotalEn:"Grand Total",
  grandTotalAr:"المجموع الإجمالي",
  En:"",
  Ar:"",
}
export const myOrderShippingDetailContent={ 
  shippingDetailsEn:"Shipping Details",
  shippingDetailsAr:"تفاصيل الشحن",
  orderCreatedEn:"Order Created",
  orderCreatedAr:"انشاء الطلب",
  orderCreatedDateEn:"27-Sep-2023",
  orderCreatedDateAr:"27-سبتمبر-2023",
  yourOrderHasBeenCreatedEn:"your order has been created it will be shipped once its confirmed.",
  yourOrderHasBeenCreatedAr:"تم إنشاء طلبك وسيتم شحنه بمجرد تأكيده.",
}