export const privacyPolicyContent = 
    {
        titlePrivacyPolicyEn:"Exchange and Returns",
        titlePrivacyPolicyAr:"سياسة الاستبدال والاسترجاع",
        lUpdateEn:"Last Update: 29/11/2023",
        lUpdateAr:"Last Update: 29/11/2023",
        subTitlePolicyEn:"The Collected Data by Visiting Nice One Website:",
        subTitlePolicyAr:"نحترم اهتمامكم فيما يتعلق بالخصوصية وقيمة علاقتنا معكم، سياسة الخصوصية هذه تصف جميع أنواع المعلومات الشخصية التي نجمعها عن عملائنا وطريقة",
        policyDetailsEn:" We respect your concern regarding the privacy policy and the value of our relationship with you. This privacy policy reflects all types of personal information we collect about our customers, how we use this information, and with whom we share. Also, the available options to our customers regarding our use of information, the standard we use to protect information, and how our customers contact us about our actions. By providing your personal information, you hereby consent to the privacy policy and agree that we may collect, use, and disclose personal information according to the privacy policy. Note that you are not obligated to provide any information we ask you to provide. However, if you do not provide us with the information we ask for, we may not be able to provide any products or services based on the collection of this information. Please exit from the website if you do not agree to the privacy policy, or if you browse the website from a country or region where using this website is blocked.",
        policyDetailsAr:"نحترم اهتمامكم فيما يتعلق بالخصوصية وقيمة علاقتنا معكم، سياسة الخصوصية هذه تصف جميع أنواع المعلومات الشخصية التي نجمعها عن عملائنا وطريقة استخدامنا للمعلومات ومع من نشاركها والخيارات المتوفرة لعملائنا بالنسبة لاستخدامنا للمعلومات والمقاييس التي نتخذها لحماية المعلومات وكيفية تواصل عملائنا معنا فيما يخص إجراءاتنا الخاصة. بتزويدك إيانا معلوماتك الشخصية، أنت تقبل بسياسة الخصوصية وتوافق على أنه يجوز لنا تجميع واستخدام المعلومات الشخصية والإفصاح عنها وفقًا لما هو وارد في سياسة الخصوصية علما بأنك غير ملزم بتقديم أي معلومات نطلب منك تقديمها ومع ذلك إذا لم تقدم لنا المعلومات التي نطلبها منك ربما لا يمكننا أن نوفر لك أي سلع أو خدمات تعتمد على تجميع هذه المعلومات، ويرجى الخروج من الموقع الإلكتروني إذا لم تقبل سياسة الخصوصية أو إذا كنت تقوم بزيارة الموقع من دولة أو إقليم يكون استخدام الموقع فيها محظورًا.",
        PolicyDetails2En:"Every time you browse Nice One website, the information is sent from your browser to Nice One server log files to be saved there. It includes the details of your visit, for example, the time and date of your visit to the website, the pages you browsed, your IP address, the email address that led you to Nice One website, the type of browser, and the operating system of the device.",
        PolicyDetails2Ar:"نحترم اهتمامكم فيما يتعلق بالخصوصية وقيمة علاقتنا معكم، سياسة الخصوصية هذه تصف جميع أنواع المعلومات الشخصية التي نجمعها عن عملائنا وطريقة استخدامنا للمعلومات ومع من نشاركها والخيارات المتوفرة لعملائنا بالنسبة لاستخدامنا للمعلومات والمقاييس التي نتخذها لحماية المعلومات وكيفية تواصل عملائنا معنا فيما يخص إجراءاتنا الخاصة. بتزويدك إيانا معلوماتك الشخصية، أنت تقبل بسياسة الخصوصية وتوافق على أنه يجوز لنا تجميع واستخدام المعلومات الشخصية والإفصاح عنها وفقًا لما هو وارد في سياسة الخصوصية علما بأنك غير ملزم بتقديم أي معلومات نطلب منك تقديمها ومع ذلك إذا لم تقدم لنا المعلومات التي نطلبها منك ربما لا يمكننا أن نوفر لك أي سلع أو خدمات تعتمد على تجميع هذه المعلومات، ويرجى الخروج من الموقع الإلكتروني إذا لم تقبل سياسة الخصوصية أو إذا كنت تقوم بزيارة الموقع من دولة أو إقليم يكون استخدام الموقع فيها محظورًا.",
        policyDetails3En:"Once you visit a page of our website that contains a social plugin your browser will create a direct link with the social plugin servers such as (Google and Facebook). Where it transfers the plugin’s content directly to your browser, which works to include this information on the website, allowing reception information relating to your access to the selected webpage. As a result, the collected data by visiting Nice One website will get transferred, and it certainly does not include any personal data as a name and a phone number. If you do not want to share your visit data with Nice One website, you can disable tracking from your browser settings",
        policyDetails3Ar:"",
    }