export const loginSideBarContent = 
    {
        forgetTextEn:'Forget password?',
        forgetTextAr:"نسيت كلمة المرور؟",
        orLoginWithEn:"or Login with",
        orLoginWithAr:"او سجل ب",
    
    }
export const addressPageContent = 
    {
        step1AddressEn:"Address",
        step1AddressAr:"العنوان",
        step2CheckOutEn:"CheckOut",
        step2CheckOutAr:"الدفع",
        step3CompleteEn:"Complete",
        step3CompleteAr:"مكتمل",
        addressPageTitleEn:"Address",
        addressPageTitleAr:"عنوان الشحن",
        addressPageBtnTextEn: "Add New Address",
        addressPageBtnTextAr:"اضف عنوان جديد",
        btnProceedToPayEn: "Proceed To Pay",
        btnProceedToPayAr:"أكمل عمليه الدفع",
        headingThereIsNoAddressEn:"There is no address, add a new address",
        headingThereIsNoAddressAr:"لا يوجد عنوان , أضف عنوان جديد",
        paymentPageUrlEn:'/payment',
        paymentPageUrlAr:'/payment',
        defaultBtnTextEn:"Default",
        defaultBtnTextAr:"الأفتراضي",
        deleteBtnTextEn:'Delete',
        deleteBtnTextAr:'مسح',
        editBtnTextEn:"Edit",
        editBtnTextAr:"تحرير",
    
    }
export const orderCompleteContent = 
    {
      step1En:"Address",
      step1Ar:"العنوان",
      step2En:"CheckOut",
      step2Ar:"الدفع",
      step3En:"Complete",
      step3Ar:"مكتمل",
      titleOrderConfirmedEn:"Thanks, Your Order Has Been Confirmed",
      titleOrderConfirmedAr:"شكرا، لقد تم تأكيد طلبك",
      orderInfoEn: "Order Number",
      orderInfoAr: "رقم الطلب " ,
      orderInfoNumEn: '6543Ca1588xs2e5',
      orderInfoNumAr: '6543Ca1588xs2e5',
      canFollowUpOrderEn:"You Can Follow up You’r Order" ,
      canFollowUpOrderAr: "يمكنك متابعه الطلب",
      btnMyOrderEn:"My Orders",
      btnMyOrderAr:"طلباتي",
      btnTextTrackEn: "Track",
      btnTextTrackAr:"تتبع",
      facebookUrlEn:"/",
      facebookUrlAr:"/",   
      instagramUrlEn:"/",
      instagramUrlAr:"/",   
      twitterUrlEn:"/",
      twitterUrlAr:"/",   
      snapUrlEn:"/",
      snapUrlAr:"/",   
      tiktokUrlEn:"/",
      tiktokUrlAr:"/",
    }

export const addAddressContent ={
    titleAddAddressEn:"Add Address",
    titleAddAddressAr:"أضافه عنوان",   
    btnAddressEn:"Add Address",
    btnAddressAr:"أضافه عنوان",   
    btnChooseMapEn:"Choose On Map",
    btnChooseMapAr:"حدد من جوجل" ,   
    btnBack3En:"Back",
    btnBack3Ar:"رجوع" ,   
    phAbdullahElzEn:"Abdullah Elzayat",
    phAbdullahElzAr:"عبدالله الزيات" ,   
    optionEn:"Optional",
    optionAr:"اختياري" ,    
    phMobNumberEn:"mobile number",
    phMobNumberAr:"رقم الهاتف",
    phSecondNumberEn:"second mobile number",
    phSecondNumberAr:"رقم الهاتف",
    placeholderCityEn:"City",
    placeholderCityAr:"مدينة" ,   
    neighborhoodPhEn: "Neighborhood name and street",
    neighborhoodPhAr: "اسم الحي والشارع",
    phSpecialEn: "Special Place",
    phSpecialAr:"مكان خاص",
    btnCompleteEn:"Complete",
    btnCompleteAr:"مكتمل",
}
export const notificationContent ={
    msgTabEn:"Messages",
    msgTabAr:"الرسائل",
    offerTabEn: "Offers",
    offerTabAr: "العروض" ,
    msgTitleEn: "The message box is empty",
    msgTitleAr:"صندوق الرسائل فارغ",
    msgSubTitleEn:"There are no new messages",
    msgSubTitleAr:"لا توجد رسائل جديدة",
    offerTitleEn: "The Offer box is empty",
    offerTitleAr:" العروض فارغ",
    offerSubTitleEn: "There are no new offers",
    offerSubTitleAr:"لا توجد عروض جديدة",
    notifyTitleEn:"Head text Here",
    notifyTitleAr:"Head text Here",
    notifyTitle2En:"Head text Here",
    notifyTitle2Ar:"Head text Here",
    notifySubTitleEn:"text lorem Heretext lorem Heretext lorem Here",
    notifySubTitleAr:"text lorem Heretext lorem Heretext lorem Here",
    notifySubTitle2En:"text lorem Heretext lorem Heretext lorem Here",
    notifySubTitle2Ar:"text lorem Heretext lorem Heretext lorem Here",
    offerNotifyTitleEn:"Head text Here offer",
    offerNotifyTitleAr:"Head text Here offer",
    offerNotifyDiscountEn:"Discount offer",
    offerNotifyDiscountAr:"Discount offer",
    ofrDiscountRateEn:"50%",
    ofrDiscountRateAr:"50%",
}
export const addedShoppingContent={
    latestProductsTitleEn: "the latest products",
    latestProductsTitleAr:"تسوق من احدث المنتجات",
    continueMarketingEn: "Continue Marketing",
    continueMarketingAr:"اذهب للتسوق" ,
    completeTheOrderEn: "Complete the Order",
    completeTheOrderAr:"اكمال الطلب" ,
}
export const AddedCheckedCartContent={
    productHasBeenAddedEn: " The product has been added to the shopping cart",
    productHasBeenAddedAr:"تمت اضافة للسلة بنجاح",
    priceIs125En: "Total :Price is 125 SAR",
    priceIs125Ar:"التكلفة الاجمالية 150 ريال",
}
export const shoppingCartSideBarContent={
  shoppingCartTitleEn:"Shopping Cart",
  shoppingCartTitleAr:"Shopping Cart",
  freeShippingEn:"Do you want free shipping to",
  freeShippingAr:"هل تريد الشحن المجاني إلى ",
  placeNameEn:"Saudi Arabia?",
  placeNameAr:"المملكة العربية السعودية؟"  ,
  freeShipping2En:"Add ",
  freeShipping2Ar:"أضف" ,
  freeShipping3En:"SAR to your cart",
  freeShipping3Ar:"ريال إلى سلة التسوق الخاصة بك",
  yourBagEn:"YOUR BAG",
  yourBagAr:"حقيبتك " ,
  sideItemEn:"ITEMS",
  sideItemAr: "عناصر", 
  titleFreeGiftEn: "My Free Gifts",   
  titleFreeGiftAr: "هداياي المجانية" ,   
  titleTheProductEn:"the latest products",   
  titleTheProductAr:"تسوق من احدث المنتجات", 
  totalPrice1950En:"Total: 3 products - 1950 riyals",  
  totalPrice1950Ar:"الإجمالي : 3 منتجات - 1950 ريال",    
  btnTextOrderEn: "Complete the Order",
  btnTextOrderAr:"اكمال الطلب" , 
  urlEn:"/payment",
  urlAr:"/payment",
}
export const emptyShoppingCartContent=
  {
    emptyCartTitleEn: "Your shopping cart is empty",
    emptyCartTitleAr:"سلة التسوق الخاصة بك فارغة!",
    emptyCartSubTitleEn:"Add some products to the cart to complete your order",
    emptyCartSubTitleAr:"أضف بعض المنتجات إلى سلة التسوق لإكمال طلبك",
  }
export const giftCartContent=
  {
    giftCartProductNameEn:"Baby Don't Cry Shampoo",
    giftCartProductNameAr:"شامبو الطفل لا تبكي",
    giftTextEn:"Pre-order Gift",
    giftTextAr:"هدية الطلب المسبق" ,
    giftNumberEn: "1",
    giftNumberAr: "1",
  }


export const productArr=[
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
]